### ISSUE TITLE
Make solution field in SegmentSolution relation a Boolean

### ISSUE THREAD

**Issue by tomka** [catsop/CATMAID#1]
There are probably a lot of entries in this table and we also have to query often whether a specific segment is part of a solution and test if this field is one or zero. For this test a Boolean field would be cleaner and faster.

**Comment by aschampion** [comment]
As of efb748bdf42f36fe1d65d8c9914445c8b0752a89 this issue no longer applies because solutions are now indicated by the existence of rows.
