### ISSUE TITLE
Segment and slice PKs are currently guaranteed to be unique for only one stack

### ISSUE THREAD

**Issue by aschampion** [catsop/CATMAID#3]
Now that the 64-bit uints are used as primary keys for segment and slice IDs in both Postgres and python-sopnet, there is the potential for key collisions between slices and segments from different stacks. This is obviously most likely for stacks with the same or similar image data, but for whatever purposes  we may want to generate segmentations/solutions independent of other stacks. Django's ORM does not support multicolumn primary keys, and a compound column PK would be large and slow. Sopnet needs more than 4-byte keys for, e.g., slices, so inserting the stack ID into the slice hash would require limiting the stack ID's size. A smallint (2-byte) key would only allow 65K stacks, when some CATMAID instances are known to already have 40K stacks, so this limitation would not work. Additionally it would force CATMAID's internal stack details back into sopnet, which is poor design.

One option is to have another 8-byte integer PK internal to postgres, and a multicolumn unique constraint/index on the stack_id/hash_value tuple, which would allow for fast lookup. Unfortunately, besides creating another 8-bytes per row for giant tables like slices, this would force all requests about segments/slices to join through those tables, even in cases where direct index lookups are possible, e.g., for conflict sets.

For now we have decided to proceed with the hash value PK/FK during the hackathon, and consider the multi-stack case an integration problem once a functional catsop is being merged with upstream CATMAID.

Please use this ticket to note places in the code where migrating the slice/segment ID later will pose problems.

**Comment by unidesigner** [comment]
Furthermore, we need to consider that the Slice table will become even more gigantic when we include slices for synapses, glial cells etc. possibly requiring another `type` column for filtering, making lookups even slower.

A possible solution that would not break 40k stacks CATMAID instances is to make particular projects CATSOP-enabled. For such projects, we create individual slice tables (and more segments etc.) for each stack and type with a naming convention. E.g. neuron_slices_stack_1 would contain only neuron slices of stack 1, glia_slices_stack_1 only slices for glia cells of stack 1 and so on. This is easy to implement in sopnet which uses pure SQL statements and knows the stack id and type of slices it operates on. And we get fast lookup, clean separation of concerns with tables making  backup or mirroring strategies simpler, and we do not break the already existing project/stack scheme for instances in production.

**Comment by aschampion** [comment]
I agree that it's best to keep the tables for each stack/type separate to ease maintenance (given the extreme size they will reach) and, more importantly, to not slow down indices by stuffing them with keys to unrelated, independent data.

Even easier and cleaner than tables with appended stack IDs would be to use stack-specific (and type-specific) schemas for each set of (dj)sopnet tables. That way all the schema creation and maintenance code is unchanged and just needs to be surrounded with changes to the schema search path (or on the sopnet side, just setting the schema path as a connection parameter). Since CATMAID lives in a default search path schema anyway (public), no changes would need to be made to the keys referencing CATMAID tables.

Unless there are any objections, I will begin implementing the schema approach soon because we are already working with two test stacks.

**Comment by unidesigner** [comment]
The stack-specific and type-specific schema approach is indeed much cleaner and better maintainable, no objection to go ahead with this. The second test stack has already more types (synapses, mitochondria) which could be used for testing.
