### ISSUE TITLE
Add ignore-on-duplicate-insert rule to djsopnet_sliceconflictset

### ISSUE THREAD

**Issue by funkey** [catsop/CATMAID#5]
Conflict sets are written multiple times to the table djsopnet_sliceconflictset when they belong to more than one block.

I wrote a migration that naively adds the "INSTEAD DO NOTHING" rule when the entry exists already. However, this brakes the inserting SQL statement that assumes that the new row was created and returns the ID. The migration can be found in the current blockwise-sopnet 083b7421c91c97def831cb79675a99631510f143 branch (which is not consistent with the database state on neurocity) and in sliceconflictset_rule 29c5581ac068ba903ce6e5342262add5d91339aa (which is consistent with neurocity).

**Comment by funkey** [comment]
I fixed it for now by issuing two queries for the insertion of slice conflicts (https://github.com/catsop/python-sopnet/commit/5f418c3fb084ce62c7a3892b26dace71c06ab65d). Someone with more SQL-superpowers might be able to join this into a single, more efficient query.

**Comment by tomka** [comment]
I believe you should be able to run both `INSERT` statements in one query by separating them with a semicolon. This would result in only one query sent to Postgres in a single transaction.

**Comment by funkey** [comment]
Sounds good.

By the way, I migrated neurocity to the latest and greates (thanks Andrew for the nice instructions) and dropped branch sliceconflictset_rule.

**Comment by funkey** [comment]
Yepp, that worked. Fixed in https://github.com/catsop/python-sopnet/commit/eb415d18cc3f9bf5ea03c67296dd9a36d5c1a3e5.
